### ISSUE TITLE
GAE部署时只能使用8080端口

### ISSUE THREAD

**Issue by mrdulin** [mrdulin/nodejs-gcp#8]
在`GAE`的配置文件`app.yaml`中无法通过`env_variables`设置`PORT`为非8080端口

访问`GAE`应用的日志：

![image](https://user-images.githubusercontent.com/17866683/48407402-b2176b00-e771-11e8-95a4-9bf01e43ceca.png)

通过日志输出看到，尽管程序是运行起来了，但是在浏览器访问路由`/`时，一直处于`pending`状态

![image](https://user-images.githubusercontent.com/17866683/48407531-fd317e00-e771-11e8-8d6b-2920da5a702c.png)

> You can define additional environment variables in your app.yaml file, but the above values cannot be overridden.

根据官方文档描述，不能修改`PORT`端口为非8080端口，`PORT`环境变量不能被非8080的其他值重写。

部署时正确配置应该如下，或者省略`PORT`，`PORT`默认为8080

```yaml
runtime: nodejs8
service: standard-env-work-with-webpack-success
env_variables:
  NODE_ENV: production
  PORT: 8080
```

参考：

- https://cloud.google.com/appengine/docs/standard/nodejs/runtime#environment_variables
